import axios from 'axios';
console.log(`Line 1`);
const api = axios.create({ baseURL: '/api' });
console.log(`Line 2`);
export const getProducts = () => api.get('/products');
console.log(`API CHECK1`);
console.log(`API CHECK ${api} ${getProducts()}`);
export const getDashboard = () => api.get('/products/dashboard');
export const getProduct = (id) => api.get(`/products/${id}`);
export const createProduct = (data) => api.post('/products', data);
export const updateProduct = (id, data) => api.put(`/products/${id}`, data);
export const deleteProduct = (id) => api.delete(`/products/${id}`);
export const generateProduct = (prompt) => api.post('/ai/generate', { prompt });
export const searchProducts = (query) => api.post('/ai/search', { query });
